dist: xenial
services:
  - docker
language: go
go:
  - "1.14.x"
os:
  - linux
  - osx

cache:
  directories:
    - $GOPATH/pkg
    - vendor

git:
  depth: 1

env:
  global:
    GOFLAGS=-mod=vendor

jobs:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - go: "1.14.x"
    name: "Code Lint"
    script: travis_wait 30 make lint
  - go: "1.14.x"
    name: "Code UnitTest"
    script: make test
  - go: "1.14.x"
    name: "Website"
    script:
      - make website-test
      - make website-lint

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

branches:
  only:
  - master
